POST http://localhost:3003/api/blogs 
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QzIiwiaWQiOiI2MThmMTJhMzJhYWE0NzYzMWM5OTBkOWEiLCJpYXQiOjE2MzY3OTM2NDksImV4cCI6MTYzNjc5NzI0OX0.R_fV08Jmt_7F_NvbxpbQCd-b6f8-paZWIPxm99aJMhs

{
    "title": "testing",
    "author": "ben",
    "url":"testing.com",
    "likes": "54",
    "user": "62d6f4e5999d16c3a2e8ae8f"
}
